
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.maliceormercy.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.maliceormercy.item.TheCorruptionItem;
import net.mcreator.maliceormercy.item.SnappedCorruptBoneItem;
import net.mcreator.maliceormercy.item.SilverCoinItem;
import net.mcreator.maliceormercy.item.SapphireSwordItem;
import net.mcreator.maliceormercy.item.SapphireShovelItem;
import net.mcreator.maliceormercy.item.SapphirePickaxeItem;
import net.mcreator.maliceormercy.item.SapphireItem;
import net.mcreator.maliceormercy.item.SapphireHoeItem;
import net.mcreator.maliceormercy.item.SapphireCoinItem;
import net.mcreator.maliceormercy.item.SapphireAxeItem;
import net.mcreator.maliceormercy.item.SapphireArmourItem;
import net.mcreator.maliceormercy.item.SapphireAppleItem;
import net.mcreator.maliceormercy.item.RubySwordItem;
import net.mcreator.maliceormercy.item.RubyShovelItem;
import net.mcreator.maliceormercy.item.RubyPickaxeItem;
import net.mcreator.maliceormercy.item.RubyItem;
import net.mcreator.maliceormercy.item.RubyHoeItem;
import net.mcreator.maliceormercy.item.RubyCoinItem;
import net.mcreator.maliceormercy.item.RubyAxeItem;
import net.mcreator.maliceormercy.item.RubyArmourItem;
import net.mcreator.maliceormercy.item.RubyAppleItem;
import net.mcreator.maliceormercy.item.QuartzCoinItem;
import net.mcreator.maliceormercy.item.OnyxCoinItem;
import net.mcreator.maliceormercy.item.LiquidCorruptionItem;
import net.mcreator.maliceormercy.item.GoldCoinItem;
import net.mcreator.maliceormercy.item.EnchantedSapphireAppleItem;
import net.mcreator.maliceormercy.item.EnchantedRubyAppleItem;
import net.mcreator.maliceormercy.item.EnchantedDiamondAppleItem;
import net.mcreator.maliceormercy.item.EnchantedAmethystAppleItem;
import net.mcreator.maliceormercy.item.EmeraldCoinItem;
import net.mcreator.maliceormercy.item.DiamondCoinItem;
import net.mcreator.maliceormercy.item.DiamondAppleItem;
import net.mcreator.maliceormercy.item.CorruptPowderItem;
import net.mcreator.maliceormercy.item.CorruptFleshItem;
import net.mcreator.maliceormercy.item.CorruptDustItem;
import net.mcreator.maliceormercy.item.CorruptBoneShardItem;
import net.mcreator.maliceormercy.item.CorruptBoneItem;
import net.mcreator.maliceormercy.item.CorruptBerriesItem;
import net.mcreator.maliceormercy.item.CopperCoinItem;
import net.mcreator.maliceormercy.item.AmethystSwordItem;
import net.mcreator.maliceormercy.item.AmethystShovelItem;
import net.mcreator.maliceormercy.item.AmethystPickaxeItem;
import net.mcreator.maliceormercy.item.AmethystHoeItem;
import net.mcreator.maliceormercy.item.AmethystCoinItem;
import net.mcreator.maliceormercy.item.AmethystAxeItem;
import net.mcreator.maliceormercy.item.AmethystArmorItem;
import net.mcreator.maliceormercy.item.AmethystAppleItem;
import net.mcreator.maliceormercy.MaliceOrMercyMod;

public class MaliceOrMercyModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MaliceOrMercyMod.MODID);
	public static final RegistryObject<Item> HUMAN_SPAWN_EGG = REGISTRY.register("human_spawn_egg", () -> new ForgeSpawnEggItem(MaliceOrMercyModEntities.HUMAN, -16729120, -16753253, new Item.Properties()));
	public static final RegistryObject<Item> CORRUPT_FIEND_SPAWN_EGG = REGISTRY.register("corrupt_fiend_spawn_egg", () -> new ForgeSpawnEggItem(MaliceOrMercyModEntities.CORRUPT_FIEND, -13368248, -11074308, new Item.Properties()));
	public static final RegistryObject<Item> COPPER_COIN = REGISTRY.register("copper_coin", () -> new CopperCoinItem());
	public static final RegistryObject<Item> SILVER_COIN = REGISTRY.register("silver_coin", () -> new SilverCoinItem());
	public static final RegistryObject<Item> GOLD_COIN = REGISTRY.register("gold_coin", () -> new GoldCoinItem());
	public static final RegistryObject<Item> EMERALD_COIN = REGISTRY.register("emerald_coin", () -> new EmeraldCoinItem());
	public static final RegistryObject<Item> DIAMOND_COIN = REGISTRY.register("diamond_coin", () -> new DiamondCoinItem());
	public static final RegistryObject<Item> AMETHYST_COIN = REGISTRY.register("amethyst_coin", () -> new AmethystCoinItem());
	public static final RegistryObject<Item> ONYX_COIN = REGISTRY.register("onyx_coin", () -> new OnyxCoinItem());
	public static final RegistryObject<Item> QUARTZ_COIN = REGISTRY.register("quartz_coin", () -> new QuartzCoinItem());
	public static final RegistryObject<Item> RUBY_COIN = REGISTRY.register("ruby_coin", () -> new RubyCoinItem());
	public static final RegistryObject<Item> SAPPHIRE_COIN = REGISTRY.register("sapphire_coin", () -> new SapphireCoinItem());
	public static final RegistryObject<Item> AMETHYST_ARMOR_HELMET = REGISTRY.register("amethyst_armor_helmet", () -> new AmethystArmorItem.Helmet());
	public static final RegistryObject<Item> AMETHYST_ARMOR_CHESTPLATE = REGISTRY.register("amethyst_armor_chestplate", () -> new AmethystArmorItem.Chestplate());
	public static final RegistryObject<Item> AMETHYST_ARMOR_LEGGINGS = REGISTRY.register("amethyst_armor_leggings", () -> new AmethystArmorItem.Leggings());
	public static final RegistryObject<Item> AMETHYST_ARMOR_BOOTS = REGISTRY.register("amethyst_armor_boots", () -> new AmethystArmorItem.Boots());
	public static final RegistryObject<Item> AMETHYST_SWORD = REGISTRY.register("amethyst_sword", () -> new AmethystSwordItem());
	public static final RegistryObject<Item> AMETHYST_AXE = REGISTRY.register("amethyst_axe", () -> new AmethystAxeItem());
	public static final RegistryObject<Item> AMETHYST_HOE = REGISTRY.register("amethyst_hoe", () -> new AmethystHoeItem());
	public static final RegistryObject<Item> AMETHYST_PICKAXE = REGISTRY.register("amethyst_pickaxe", () -> new AmethystPickaxeItem());
	public static final RegistryObject<Item> AMETHYST_SHOVEL = REGISTRY.register("amethyst_shovel", () -> new AmethystShovelItem());
	public static final RegistryObject<Item> RUBY = REGISTRY.register("ruby", () -> new RubyItem());
	public static final RegistryObject<Item> RUBY_ARMOUR_HELMET = REGISTRY.register("ruby_armour_helmet", () -> new RubyArmourItem.Helmet());
	public static final RegistryObject<Item> RUBY_ARMOUR_CHESTPLATE = REGISTRY.register("ruby_armour_chestplate", () -> new RubyArmourItem.Chestplate());
	public static final RegistryObject<Item> RUBY_ARMOUR_LEGGINGS = REGISTRY.register("ruby_armour_leggings", () -> new RubyArmourItem.Leggings());
	public static final RegistryObject<Item> RUBY_ARMOUR_BOOTS = REGISTRY.register("ruby_armour_boots", () -> new RubyArmourItem.Boots());
	public static final RegistryObject<Item> RUBY_SWORD = REGISTRY.register("ruby_sword", () -> new RubySwordItem());
	public static final RegistryObject<Item> RUBY_AXE = REGISTRY.register("ruby_axe", () -> new RubyAxeItem());
	public static final RegistryObject<Item> RUBY_HOE = REGISTRY.register("ruby_hoe", () -> new RubyHoeItem());
	public static final RegistryObject<Item> RUBY_PICKAXE = REGISTRY.register("ruby_pickaxe", () -> new RubyPickaxeItem());
	public static final RegistryObject<Item> RUBY_SHOVEL = REGISTRY.register("ruby_shovel", () -> new RubyShovelItem());
	public static final RegistryObject<Item> CORRUPT_FLESH = REGISTRY.register("corrupt_flesh", () -> new CorruptFleshItem());
	public static final RegistryObject<Item> CORRUPT_HOUND_SPAWN_EGG = REGISTRY.register("corrupt_hound_spawn_egg", () -> new ForgeSpawnEggItem(MaliceOrMercyModEntities.CORRUPT_HOUND, -13368248, -11992985, new Item.Properties()));
	public static final RegistryObject<Item> CORRUPT_BEAST_SPAWN_EGG = REGISTRY.register("corrupt_beast_spawn_egg", () -> new ForgeSpawnEggItem(MaliceOrMercyModEntities.CORRUPT_BEAST, -13368248, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> CORRUPT_TORMENTOR_SPAWN_EGG = REGISTRY.register("corrupt_tormentor_spawn_egg", () -> new ForgeSpawnEggItem(MaliceOrMercyModEntities.CORRUPT_TORMENTOR, -13368248, -3718145, new Item.Properties()));
	public static final RegistryObject<Item> AMETHYST_APPLE = REGISTRY.register("amethyst_apple", () -> new AmethystAppleItem());
	public static final RegistryObject<Item> RUBY_APPLE = REGISTRY.register("ruby_apple", () -> new RubyAppleItem());
	public static final RegistryObject<Item> BLOCK_OF_RUBY = block(MaliceOrMercyModBlocks.BLOCK_OF_RUBY);
	public static final RegistryObject<Item> LIQUID_CORRUPTION_BUCKET = REGISTRY.register("liquid_corruption_bucket", () -> new LiquidCorruptionItem());
	public static final RegistryObject<Item> CORRUPT_STONE = block(MaliceOrMercyModBlocks.CORRUPT_STONE);
	public static final RegistryObject<Item> CORRUPT_NYLIUM = block(MaliceOrMercyModBlocks.CORRUPT_NYLIUM);
	public static final RegistryObject<Item> THE_CORRUPTION = REGISTRY.register("the_corruption", () -> new TheCorruptionItem());
	public static final RegistryObject<Item> CORRUPT_FIRE = block(MaliceOrMercyModBlocks.CORRUPT_FIRE);
	public static final RegistryObject<Item> CORRUPT_BONE = REGISTRY.register("corrupt_bone", () -> new CorruptBoneItem());
	public static final RegistryObject<Item> SAPPHIRE = REGISTRY.register("sapphire", () -> new SapphireItem());
	public static final RegistryObject<Item> BLOCK_OF_SAPPHIRE = block(MaliceOrMercyModBlocks.BLOCK_OF_SAPPHIRE);
	public static final RegistryObject<Item> CORRUPT_LOG = block(MaliceOrMercyModBlocks.CORRUPT_LOG);
	public static final RegistryObject<Item> CORRUPT_PLANKS = block(MaliceOrMercyModBlocks.CORRUPT_PLANKS);
	public static final RegistryObject<Item> CORRUPT_STAIRS = block(MaliceOrMercyModBlocks.CORRUPT_STAIRS);
	public static final RegistryObject<Item> CORRUPT_SLAB = block(MaliceOrMercyModBlocks.CORRUPT_SLAB);
	public static final RegistryObject<Item> CORRUPT_FENCE = block(MaliceOrMercyModBlocks.CORRUPT_FENCE);
	public static final RegistryObject<Item> CORRUPT_FENCE_GATE = block(MaliceOrMercyModBlocks.CORRUPT_FENCE_GATE);
	public static final RegistryObject<Item> CORRUPT_ROOTS = block(MaliceOrMercyModBlocks.CORRUPT_ROOTS);
	public static final RegistryObject<Item> RUBY_ORE = block(MaliceOrMercyModBlocks.RUBY_ORE);
	public static final RegistryObject<Item> SAPPHIRE_ORE = block(MaliceOrMercyModBlocks.SAPPHIRE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_RUBY_ORE = block(MaliceOrMercyModBlocks.DEEPSLATE_RUBY_ORE);
	public static final RegistryObject<Item> DEEPSLATE_SAPPHIRE_ORE = block(MaliceOrMercyModBlocks.DEEPSLATE_SAPPHIRE_ORE);
	public static final RegistryObject<Item> SAPPHIRE_ARMOUR_HELMET = REGISTRY.register("sapphire_armour_helmet", () -> new SapphireArmourItem.Helmet());
	public static final RegistryObject<Item> SAPPHIRE_ARMOUR_CHESTPLATE = REGISTRY.register("sapphire_armour_chestplate", () -> new SapphireArmourItem.Chestplate());
	public static final RegistryObject<Item> SAPPHIRE_ARMOUR_LEGGINGS = REGISTRY.register("sapphire_armour_leggings", () -> new SapphireArmourItem.Leggings());
	public static final RegistryObject<Item> SAPPHIRE_ARMOUR_BOOTS = REGISTRY.register("sapphire_armour_boots", () -> new SapphireArmourItem.Boots());
	public static final RegistryObject<Item> SAPPHIRE_SWORD = REGISTRY.register("sapphire_sword", () -> new SapphireSwordItem());
	public static final RegistryObject<Item> SAPPHIRE_AXE = REGISTRY.register("sapphire_axe", () -> new SapphireAxeItem());
	public static final RegistryObject<Item> SAPPHIRE_HOE = REGISTRY.register("sapphire_hoe", () -> new SapphireHoeItem());
	public static final RegistryObject<Item> SAPPHIRE_PICKAXE = REGISTRY.register("sapphire_pickaxe", () -> new SapphirePickaxeItem());
	public static final RegistryObject<Item> SAPPHIRE_SHOVEL = REGISTRY.register("sapphire_shovel", () -> new SapphireShovelItem());
	public static final RegistryObject<Item> CORRUPT_SCALE = block(MaliceOrMercyModBlocks.CORRUPT_SCALE);
	public static final RegistryObject<Item> CORRUPT_BERRIES = REGISTRY.register("corrupt_berries", () -> new CorruptBerriesItem());
	public static final RegistryObject<Item> CORRUPT_BERRY_VINE = block(MaliceOrMercyModBlocks.CORRUPT_BERRY_VINE);
	public static final RegistryObject<Item> CORRUPT_DUST = REGISTRY.register("corrupt_dust", () -> new CorruptDustItem());
	public static final RegistryObject<Item> CORRUPT_POWDER = REGISTRY.register("corrupt_powder", () -> new CorruptPowderItem());
	public static final RegistryObject<Item> SNAPPED_CORRUPT_BONE = REGISTRY.register("snapped_corrupt_bone", () -> new SnappedCorruptBoneItem());
	public static final RegistryObject<Item> CORRUPT_SPIDER_SPAWN_EGG = REGISTRY.register("corrupt_spider_spawn_egg", () -> new ForgeSpawnEggItem(MaliceOrMercyModEntities.CORRUPT_SPIDER, -13368248, -3355444, new Item.Properties()));
	public static final RegistryObject<Item> CORRUPT_BONE_SHARD = REGISTRY.register("corrupt_bone_shard", () -> new CorruptBoneShardItem());
	public static final RegistryObject<Item> ENCHANTED_AMETHYST_APPLE = REGISTRY.register("enchanted_amethyst_apple", () -> new EnchantedAmethystAppleItem());
	public static final RegistryObject<Item> ENCHANTED_RUBY_APPLE = REGISTRY.register("enchanted_ruby_apple", () -> new EnchantedRubyAppleItem());
	public static final RegistryObject<Item> SAPPHIRE_APPLE = REGISTRY.register("sapphire_apple", () -> new SapphireAppleItem());
	public static final RegistryObject<Item> ENCHANTED_SAPPHIRE_APPLE = REGISTRY.register("enchanted_sapphire_apple", () -> new EnchantedSapphireAppleItem());
	public static final RegistryObject<Item> DIAMOND_APPLE = REGISTRY.register("diamond_apple", () -> new DiamondAppleItem());
	public static final RegistryObject<Item> ENCHANTED_DIAMOND_APPLE = REGISTRY.register("enchanted_diamond_apple", () -> new EnchantedDiamondAppleItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
